### ISSUE TITLE
aws cli should be configured to output JSON

### ISSUE THREAD

**Issue by vbichkovsky** [tkb-/glaciertools#13]
Documentation doesn't say that this is a requirement. So, in case aws cli was already pre-configured to output text, the tool won't work.

**Comment by numblr** [comment]
Hi,

Thanks for the hint. Does the fix on this [branch](https://github.com/numblr/glaciertools/tree/issue/13) solve your issue, or do you for some reason need the final output to respect the configured output format?

Best,
Thomas

**Comment by vbichkovsky** [comment]
Hello! Thank you for the quick response! Unfortunately, I could not do the real test (already finished the job by re-configuring aws to output JSON and stopped the server). As for the final output, I have no reasons to require it to respect the configured output format.

**Comment by numblr** [comment]
Ok, I'll test it and then merge the fix to master. Thanks again for the input :)
