### ISSUE TITLE
Won't upload all files in directory

### ISSUE THREAD

**Issue by 80kk** [tkb-/glaciertools#15]
I have a folder with sub folders and files in root as well as each sub folder. 
For instance I have 9 files in /folder/subfolder/ all of them are 1MB to 68GB big. For some reason when I am trying to upload them to the Glacier, only one file is uploaded - always the same which is 761MB big. I tried to adjust chunk size but with no change. The command I am using is:
./glacierupload -p default -v vaultname -s 8 /folder/subfolder/*

**Comment by numblr** [comment]
Hey,

I need to take a closer look into using the script with a wildcard, but I think the script doesn't really support uploading multiple files at once. You can work around it by just using the shell to call the command for each file, something like this should work:
`> for f in  /folder/subfolder/*; do ./glacierupload -p default -v vaultname -s 8 "$f"; done`
The chunk size only determines the size of the chunks in the multiple upload. With your setting of 8 it will upload each file in chunks of 2^8=256MB. It shouldn't be a problem if chunk size is larger than the file size, but it must be less than 4GB.

**Comment by numblr** [comment]
Fixed in #16, supports now multiple files.
