### ISSUE TITLE
Max level 12

### ISSUE THREAD

**Issue by O-DAREK** [tkb-/glaciertools#20]
I noticed that max part size parameter can be 12 not 22. Otherwise
"An error occurred (InvalidParameterValueException) when calling the InitiateMultipartUpload operation: Invalid part size: 17179869184. Part size must not be null, must be a power of two and be between 1048576 and 4294967296 bytes."
I think the problem is here:
Line 16: MB=1048576
...
Line 123: local -r part_size=$(( 2**split_size * MB ))

so 1048576*2^split_size=4 398 046 511 104 (for 22) which is way too much (4 294 967 296)
I may correct that,

**Comment by numblr** [comment]
Thanks for spotting and fixing this, you are correct. I merged your PR.
