### ISSUE TITLE
Remove dependency on jq

### ISSUE THREAD

**Issue by numblr** [tkb-/glaciertools#3]
We only need jq to parse the upload and archive ids, that should be rather straight forward with a regex as well and removing it gives is one dependency less.

**Comment by spartantri** [comment]
Hi @numblr why not adding simply into the aws command `--query 'uploadId' --output text` and take the value directly so you can drop jq dependency?

**Comment by numblr** [comment]
Hi, thanks for the hint, that sounds like a good solution :) I'll try your suggested once I get to it (a pull request is of course also welcome ;).
